### ISSUE TITLE
`oasis3-mct` fails to build with Intel oneAPI compiler (`2024.2.1`)

### ISSUE THREAD

**Issue by manodeep** [ACCESS-NRI/spack-packages#197]
The details of the failure are noted in [this comment](https://github.com/ACCESS-NRI/ACCESS-ESM1.6/issues/46#issuecomment-2664445217)

My experience with using the `oasis3-mct` native build system + oneAPI was a `configure` error, and then an internal compiler error. The spack build seems to produce a different error here. 

Related: The upstream `cerfacs/oasis3-mct` compiles with oneAPI out of the box and also has options for compiling as a shared library - might be worth considering by the model-dev team to update the package to the upstream version

**Comment by harshula** [comment]
Internal compiler error (%oneapi@2025.0.4):
```
/tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/src/mod_oasis_method.F90(652): error #5623: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
   tag=ICHAR(TRIM(compnm))+ICHAR(TRIM(cdnam))
-------^
compilation aborted for /tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/src/mod_oasis_method.F90 (code 3)
```

```
[root@bb4c33d99db2 opt]# spack -V
0.22.5 (a3269bae852e152d0a4e5faf64fbf8c1c0341ace)

[root@bb4c33d99db2 opt]# spack install oasis3-mct %oneapi@2025.0.4 target=x86_64
...
==> Installing oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl [35/35]
==> No binary for oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl found: installing from source
==> No patches needed for oasis3-mct
==> oasis3-mct: Executing phase: 'edit'
==> oasis3-mct: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-f' 'TopMakefileOasis3'

3 errors found in build log:
     428             #23 0x00005558ab0c519e
     429    
     430    /tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlps
            fap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/src/mod_oasis_method.F90
            (652): error #5623: **Internal compiler error: internal abort** Ple
            ase report this error along with the circumstances in which it occu
            rred in a Software Problem Report.  Note: File and line given may n
            ot be explicit cause of this error.
     431       tag=ICHAR(TRIM(compnm))+ICHAR(TRIM(cdnam))
     432    -------^
     433    compilation aborted for /tmp/root/spack-stage/spack-stage-oasis3-mc
            t-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/
            src/mod_oasis_method.F90 (code 3)
  >> 434    make[2]: *** [Makefile:30: mod_oasis_method.o] Error 3
     435    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-oasis
            3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/compile
            _oa3-mct/build/lib/psmile.MPI1'
  >> 436    make[1]: *** [TopMakefileOasis3:77: makepsmile] Error 2
     437    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-oasis
            3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/util/ma
            ke_dir'
  >> 438    make: *** [TopMakefileOasis3:30: default] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-build-out.txt
```

**Comment by harshula** [comment]
Hi @manodeep , Internal compiler error (with %oneapi@2025.0.4):
```
/tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/src/mod_oasis_method.F90(652): error #5623: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
   tag=ICHAR(TRIM(compnm))+ICHAR(TRIM(cdnam))
-------^
compilation aborted for /tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/src/mod_oasis_method.F90 (code 3)
```

```
[root@bb4c33d99db2 opt]# spack -V
0.22.5 (a3269bae852e152d0a4e5faf64fbf8c1c0341ace)

[root@bb4c33d99db2 opt]# spack install oasis3-mct %oneapi@2025.0.4 target=x86_64
...
==> Installing oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl [35/35]
==> No binary for oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl found: installing from source
==> No patches needed for oasis3-mct
==> oasis3-mct: Executing phase: 'edit'
==> oasis3-mct: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-f' 'TopMakefileOasis3'

3 errors found in build log:
     428             #23 0x00005558ab0c519e
     429    
     430    /tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlps
            fap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/src/mod_oasis_method.F90
            (652): error #5623: **Internal compiler error: internal abort** Ple
            ase report this error along with the circumstances in which it occu
            rred in a Software Problem Report.  Note: File and line given may n
            ot be explicit cause of this error.
     431       tag=ICHAR(TRIM(compnm))+ICHAR(TRIM(cdnam))
     432    -------^
     433    compilation aborted for /tmp/root/spack-stage/spack-stage-oasis3-mc
            t-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/lib/psmile/
            src/mod_oasis_method.F90 (code 3)
  >> 434    make[2]: *** [Makefile:30: mod_oasis_method.o] Error 3
     435    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-oasis
            3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/compile
            _oa3-mct/build/lib/psmile.MPI1'
  >> 436    make[1]: *** [TopMakefileOasis3:77: makepsmile] Error 2
     437    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-oasis
            3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-src/util/ma
            ke_dir'
  >> 438    make: *** [TopMakefileOasis3:30: default] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-oasis3-mct-access-om2-lfrklgomlpsfap7ijcwomhkn4xmi6apl/spack-build-out.txt
```

**Comment by manodeep** [comment]
@harshula Thanks for checking. Looks like we will need to apply the fix for the ICE I noted here: https://github.com/ACCESS-NRI/spack-packages/issues/52#issuecomment-2638219241

What's the procedure for i) updating the `oasis3-mct` source and ii) updating the git refs that submodules/spack packages might be using.

**Comment by harshula** [comment]
Hi @manodeep , You only need to fix ACCESS-NRI's `oasis3-mct` in its git repository and then create a PR.

**Comment by manodeep** [comment]
Great! I will do that then.

**Comment by harshula** [comment]
NOTABUG in the Spack Package Recipe (SPR).
